<42tig>[Auto-push](23): this is an automatic push

diff --git a/.tig/git/push_pull/Makefile b/.tig/git/push_pull/Makefile
--- a/.tig/git/push_pull/Makefile
+++ b/.tig/git/push_pull/Makefile
@@ -1,3 +1,9 @@
+define push_to_github
+	git add .
+	@echo 'git commit -m "$1" && git push'
+	@(git commit -m "$1" && git push && echo "$(call textObj,git push:)$(CURRENT_DIR) $(call textOk,OK)")|| echo "$(call textObj,git push:)$(CURRENT_DIR) $(call textError,KO)"
+endef
+
 define git_push_childs
 	@echo "\n------------------------------"
 	$(call echoObj,git push:,$1)
@@ -6,16 +12,14 @@ define git_push_childs
 	else \
 		echo "Le fichier $(call textObj,$1/Makefile)est réquise!"; \
 	fi
-	
+
 endef
 
 define git_push
 	@$(foreach moduleName,$(REPOS_NAMES),$(call git_push_childs,$(moduleName),$1))
 	@echo "\n------------------------------"
 	$(call echoObj,git push:,$(CURRENT_DIR))
-	git add .
-	@echo 'git commit -m "$1" && git push'
-	@(git commit -m "$1" && git push && echo "$(call textObj,git push:)$(CURRENT_DIR) $(call textOk,OK)")|| echo "$(call textObj,git push:)$(CURRENT_DIR) $(call textError,KO)"
+	$(call push_to_github,$1)
 endef
 
 define git_push_auto
